In [1]:
import numpy as np

In [37]:
def my_func(a):
...     """Average first and last element of a 1-D array"""
...     #return (a[0] + a[-1])  * 0.5
    # np.apply_along_axis(my_func, 0, b) - do row-wise operations
    # return (a[0:][1] + 20) - a[0:] across an entire row, [1] the 2nd row
    return (sum(a[0:-1][1])      

SyntaxError: unexpected EOF while parsing (<ipython-input-37-ba1cb2498989>, line 6)

In [3]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.apply_along_axis(my_func, 0, b)

array([4, 5, 6])

In [30]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
print(b[1].sum()/ len(b[1]) )

5.0


In [51]:
np.average(b[:][1],axis=1)

IndexError: tuple index out of range