In [1]:
import numpy as np

In [31]:
def my_func(a):
...     """Average first and last element of a 1-D array"""
...     #return (a[0] + a[-1])  * 0.5
    # np.apply_along_axis(my_func, 0, b) - do row-wise operations
    # return (a[0:][1] + 20) - a[0:] across an entire row, [1] the 2nd row
    return (a[0:][1] + 20)      

In [3]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
np.apply_along_axis(my_func, 0, b)

array([24, 25, 26])

In [30]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])